-- Alter tables para los meses en latino
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
ALTER SESSION SET NLS_LANGUAGE = 'SPANISH';
ALTER SESSION SET NLS_CURRENCY = '$';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';

-- CASO 1: Listado de Clientes

SELECT
    TRIM(TO_CHAR(C.NUMRUN, '99G999G999', 'NLS_NUMERIC_CHARACTERS='',.''')) || '-' || C.DVRUN AS "RUT Cliente",
    INITCAP(C.PNOMBRE || ' ' || C.APPATERNO) AS "Nombre Cliente",
    UPPER(PO.NOMBRE_PROF_OFIC) AS "Profesión Cliente",
    TO_CHAR(C.FECHA_INSCRIPCION, 'DD-MM-YYYY') AS "Fecha de Inscripción",
    C.DIRECCION AS "Dirección Cliente"
FROM
    CLIENTE C
    JOIN TIPO_CLIENTE TC ON C.COD_TIPO_CLIENTE = TC.COD_TIPO_CLIENTE
    JOIN PROFESION_OFICIO PO ON C.COD_PROF_OFIC = PO.COD_PROF_OFIC
WHERE
    LOWER(TC.NOMBRE_TIPO_CLIENTE) LIKE '%trabajadores dependientes%'
    AND UPPER(PO.NOMBRE_PROF_OFIC) IN ('CONTADOR', 'VENDEDOR')
    AND EXTRACT(YEAR FROM C.FECHA_INSCRIPCION) > (
        SELECT ROUND(AVG(EXTRACT(YEAR FROM FECHA_INSCRIPCION))) FROM CLIENTE
    )
ORDER BY
    C.NUMRUN ASC;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENTES_CUPOS_COMPRA';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
-- Caso 2:  aumento de credito 

CREATE TABLE CLIENTES_CUPOS_COMPRA AS
SELECT
    C.NUMRUN || '-' || C.DVRUN AS "RUT_CLIENTE",
    TRUNC(MONTHS_BETWEEN(SYSDATE, C.FECHA_NACIMIENTO)/12) AS "EDAD",
    TRIM(TO_CHAR(TCJ.CUPO_DISP_COMPRA, 'FML999G999G999', 'NLS_CURRENCY=''$'' NLS_NUMERIC_CHARACTERS='',.''')) AS "CUPO_DISPONIBLE_COMPRA",
    UPPER(TP.NOMBRE_TIPO_CLIENTE) AS "TIPO_CLIENTE"
FROM
    CLIENTE C
    JOIN TARJETA_CLIENTE TCJ ON C.NUMRUN = TCJ.NUMRUN
    JOIN TIPO_CLIENTE TP ON C.COD_TIPO_CLIENTE = TP.COD_TIPO_CLIENTE
WHERE
    TCJ.CUPO_DISP_COMPRA >= (
        SELECT MAX(CUPO_DISP_COMPRA)
        FROM TARJETA_CLIENTE
        WHERE EXTRACT(YEAR FROM FECHA_SOLIC_TARJETA) = EXTRACT(YEAR FROM SYSDATE) - 1
    )
ORDER BY
    2 ASC;

SELECT * FROM CLIENTES_CUPOS_COMPRA;
